packages:
  - playground/*

catalogs:
  autoimport:
    unplugin-auto-import: 20.2.0
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': 27.0.1
    '@antfu/utils': 9.3.0
    '@types/debug': ^4.1.12
    '@types/fs-extra': ^11.0.4
    '@types/node': 22.19.0
    bumpp: ^10.3.1
    eslint: 9.39.1
    esno: ^4.8.0
    npm-run-all: ^4.1.5
    rimraf: 6.1.0
    unbuild: ^3.6.1
    vitest: ^4.0.8
  mcp:
    '@modelcontextprotocol/sdk': ^1.21.1
    pathe: ^2.0.3
    zod: ^3.23.8
  prod:
    '@rollup/plugin-strip': ^3.0.4
    debug: ^4.4.3
    kolorist: ^1.8.0
    sirv: 3.0.2
    ufo: 1.6.1
  react:
    '@types/react': 19.2.2
    '@types/react-dom': 19.2.2
    '@vitejs/plugin-react': 5.1.0
    react: 19.2.0
    react-dom: 19.2.0
    react-router-dom: 7.9.5
  typescript:
    typescript: ^5.9.3
  vite:
    vite: ^7.2.2
  vue:
    '@vitejs/plugin-vue': ^6.0.1
    vue: 3.5.24
onlyBuiltDependencies:
  - esbuild
